// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwnsogayrvznabxthade.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3bnNvZ2F5cnZ6bmFieHRoYWRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5ODc0ODUsImV4cCI6MjA1NzU2MzQ4NX0.KgpKY0CBRKv2BBdhsB9KC7UxTCsgg_ve2-yrlNcKg04";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);